### ISSUE TITLE
Pattern ends after every ")", not just the last one.

### ISSUE THREAD

**Issue by Tobi-La** [kuzyn/chatscript-tmlanguage#46]
I hoften have patterns where I use nested patterns, like this one:

![chatscriptsublime](https://cloud.githubusercontent.com/assets/25849067/23074569/6f39edca-f539-11e6-8c9c-00b9f7650de4.PNG)

The patterns should not end after the first ")".

Thank you so much, great plugin, makes working with chatscript a lot easier! :)

**Comment by kuzyn** [comment]
Indeed that's a bug. I've opened and issue for that already as #34 so I'll close this one. Hopefully I should be able to get to it for 1.3.0
